trigger:
- master

jobs:
  - job: linux
    timeoutInMinutes: 10  # does not cause a failure, unfortunately
    pool:
      vmImage: 'ubuntu-latest'
    strategy:
      matrix:
        # geoip2 is >= 3.6
        Python36:
          python.version: '3.6'
        Python36loglevel:
          python.version: '3.6'
          myenv: COCRAWLER_LOGLEVEL=DEBUG
        Python36asyncdebug:
          python.version: '3.6'
          myenv: PYTHONASYNCIODEBUG=1
        Python37:
          python.version: '3.7'
        Python38:
          python.version: '3.8'
        # 3.9 is a reppy build fail

    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(python.version)'
      displayName: 'Use Python $(python.version)'

    - script: |
        python -m pip install --upgrade pip
        pip install . .[test]
      displayName: 'Install dependencies'

    - script: |
        set -e
        if [ ! -z "$(myenv)" ]; then
          export $(myenv)
        fi
        make test_coverage
      displayName: 'pytest'

    - script: |
        printenv
        #pip install coveralls
        pip install git+https://github.com/wumpus/coveralls-python
        export CIRCLE_BRANCH=$BUILD_SOURCEBRANCH
        coveralls -v
        git rev-parse --abbrev-ref HEAD
      displayName: 'coveralls'
      env:
        CIRCLECI: 1
        CIRCLE_BUILD_NUM: $(Build.BuildNumber)
        COVERALLS_REPO_TOKEN: $(coveralls_repo_token)

  - job: macos
    timeoutInMinutes: 10  # does not cause a failure, unfortunately
    pool:
      vmImage: 'macOS-latest'
    strategy:
      matrix:
        Python38:
          python.version: '3.8'

    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(python.version)'
      displayName: 'Use Python $(python.version)'

    - script: |
        python -m pip install --upgrade pip
        pip install . .[test]
      displayName: 'Install dependencies'

    - script: |
        set -e
        if [ ! -z "$(myenv)" ]; then
          export $(myenv)
        fi
        make test_coverage
        coverage report
      displayName: 'pytest'

    - script: |
        printenv
        #pip install coveralls
        pip install git+https://github.com/wumpus/coveralls-python
        export CIRCLE_BRANCH=$BUILD_SOURCEBRANCH
        coveralls -v
        git rev-parse --abbrev-ref HEAD
      displayName: 'coveralls'
      env:
        CIRCLECI: 1
        CIRCLE_BUILD_NUM: $(Build.BuildNumber)
        COVERALLS_REPO_TOKEN: $(coveralls_repo_token)
