name: test-all

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  linux-macos:
    name: test-all ${{ matrix.os }} ${{ matrix.python-version }} ${{ matrix.VERBOSE }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: [3.7, 3.8]  # no reppy wheel: , 3.9, '3.10']
        EXTRA: [false]  # used to force includes to get included
        include:
          - python-version: 3.8
            os: ubuntu-latest
            # make sure that the most verbose level is not crashy
            COCRAWLER_LOGLEVEL: DEBUG
            PYTHONASYNCIODEBUG: 1
            VERBOSE: verbose
            EXTRA: true
          - python-version: 3.8
            os: ubuntu-latest
            # make sure that exact versions still work
            EXACT_VERSIONS: 1
            EXTRA: true
          - python-version: 3.8
            os: macos-latest

    environment: cocrawler-test

    steps:

    - uses: actions/checkout@v3
    - name: set up python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64

    - name: 'Install dependencies'
      run: |
        python -m pip install --upgrade pip
        pip install . .[test]

    - name: 'Install exact version if needed'
      if: ${{ matrix.EXACT_VERSIONS }}
      run: |
        pip install -r requirements.txt

    - name: 'pytest'
      run: |
        make test_coverage
      env:
        COCRAWLER_LOGLEVEL: ${{ matrix.COCRAWLER_LOGLEVEL }}
        PYTHONASYNCIODEBUG: ${{ matrix.PYTHONASYNCIODEBUG }}

    - name: 'coveralls'
      run: |
        pip install coveralls
        coveralls
      env:
        CIRCLECI: 1
        CIRCLE_BRANCH: ${{ env.GITHUB_REF_NAME }}
        CIRCLE_BUILD_NUM: ${{ env.GITHUB_RUN_NUMBER }}
        # github -> settings -> environments -> cocrawler-test
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
